---
title: "First Knit"
author: "Chris Gonzalez"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended Palmdale High School and graduated in 2008. English class presents more difficulty for me due to it being my second language. However, I find math enjoyable because numbers are a universal language. In terms of performance, I excelled in the math subject.

## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
For this class, I am using a Windows computer. On a scale of 1 to 10, with 1 being a total beginner and 10 being an expert, I would rate myself as a 6 in computer knowledge. My internet connection at home is always available and reliable.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefer to be called by my first name, Chris, both by my classmates and the instructor.
   
 
## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
In life, my goal is to live comfortably and take care of my wife and sons. I have a great interest in the medical field and aspire to become a respiratory therapist.
   

## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
I have visited Mexico before, but I would love to visit Japan in the future due to my deep admiration and respect for its culture. I do not have a military background.
  

## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
I did not take Math 115 or Math 116. However, I am aware that Math 115 only fulfills a general education requirement. My goal is to successfully complete this statistics class to meet the requirements for the respiratory therapy program.
 






  




